### ISSUE TITLE
[BUG] get_board() fails to connect to websocket

### ISSUE THREAD

**Issue by tryptech** [WorldObservationLog/reddit-place-script-2023#1]
# Bug Report Form

## Checklist

- [X] I am using the latest version of the code.
- [X] I am absolutely sure I read the README in its entirety.
- [X] I have made sure this is not a duplicate issue.
- [X] I have filled out this form correctly.

## Describe the bug

After successful authorization, each worker fails to connect to the websocket.

`2023-07-21 11:26:59.540 | ERROR    | __main__:get_board:197 - Failed to connect to websocket, trying again in 30 seconds...`

## To Reproduce

Steps to trigger the bug:

1. Run script
2. Wait for successful authorization
3. See error when attempting to connect to websocket in get_board()

**Comment by WorldObservationLog** [comment]
Can't reproduce, please add -d parameter when running and send logs to me

**Comment by tryptech** [comment]
It was an SSLCertVerification error that was resolved here https://github.com/marckopop/reddit-place-script-2023/commit/75ff87d8329fc675065b436c59d48dbf00c72915
