### ISSUE TITLE
The Colors of the bot is mismatched somehow

### ISSUE THREAD

**Issue by That-SkyKid** [WorldObservationLog/reddit-place-script-2023#11]
![image](https://github.com/WorldObservationLog/reddit-place-script-2023/assets/35163124/0899fb2d-67b2-4921-9f0f-fe8df21ab74b)

![image](https://github.com/WorldObservationLog/reddit-place-script-2023/assets/35163124/155f28cd-9a7e-4dd9-8b30-49757a53dc68)

Colors of the bot trying to put is mismatched and sometimes the bot won't detect the existing of the color and replaces it anyway.

**Comment by WorldObservationLog** [comment]
The color transform function uses an algorithm to calculate the similarity of colors. It will transfer your image pixel's color into a numerically similar color. So it may seem not like the origin color.
For your secong problem, it's an old bug (https://github.com/rdeepak2002/reddit-place-script-2022/issues/364) and I have no idea how to fix it. You can raise the thread_delay value or mannually set start_coords of every account.

**Comment by That-SkyKid** [comment]
> The color transform function uses an algorithm to calculate the similarity of colors. It will transfer your image pixel's color into a numerically similar color. So it may seem not like the origin color.
> For your secong problem, it's an old bug (https://github.com/rdeepak2002/reddit-place-script-2022/issues/364) and I have no idea how to fix it. You can raise the thread_delay value or mannually set start_coords of every account.

What did you mean manually set start_coords on every account?

**Comment by WorldObservationLog** [comment]
Setting start_coords ,every accont will place different area pixels instead of upper left area. This will help ease the problem.

**Comment by That-SkyKid** [comment]
> Setting start_coords ,every accont will place different area pixels instead of upper left area. This will help ease the problem.

So, I can give each account a area to draw. Can you illustrate? I don't understand.

**Comment by WorldObservationLog** [comment]
Suppose we have an 5x3 image where each pixel is represented by a letter like this:
a b c d e
f g h i j
k l m n o

if i set an account's start_coords to [0,1], it will start placeing from pixel f. and if start_coords is [2,1], it will start placeing from pixel h (zero-based count).

**Comment by That-SkyKid** [comment]
> Suppose we have an 5x3 image where each pixel is represented by a letter like this:
> a b c d e
> f g h i j
> k l m n o
> 
> if i set an account's start_coords to [0,1], it will start placeing from pixel f. and if start_coords is [2,1], it will start placeing from pixel h (zero-based count).

How this suppose to fix the issue if the script will and always put h pixel on that account?

**Comment by WorldObservationLog** [comment]
> > Suppose we have an 5x3 image where each pixel is represented by a letter like this:
> > a b c d e
> > f g h i j
> > k l m n o
> > if i set an account's start_coords to [0,1], it will start placeing from pixel f. and if start_coords is [2,1], it will start placeing from pixel h (zero-based count).
> 
> How this suppose to fix the issue if the script will and always put h pixel on that account?

Just ease, it cannot actually solve the problem.
The real problem is that the task of getting board image is not sync with the placing tasks.
