### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Yharoses** [WorldObservationLog/reddit-place-script-2023#14]
# Bug Report Form

## Checklist

- [x] I am using the latest version of the code.
- [x] I am absolutely sure I read the README in its entirety.
- [x] I have made sure this is not a duplicate issue.
- [x] I have filled out this form correctly.

## Describe the bug

Whenever I try to use the bot it gives me an error that says it could not open the requirements file: [Errno 2] No such file or directory: 'requirements.txt'

## To Reproduce

Steps to trigger the bug:

1. Go to 'reddit-place-script-2023-main'
2. Click on 'start'
3. Wait a second

## Expected behavior

The bot should start working

**Comment by Antoine489** [comment]
Hey you have the file requirements.txt in script directory ?

**Comment by Yharoses** [comment]
Yeah, the file is there, i haven't even touched it

**Comment by mondomonmon** [comment]
Go into a command line, go to the scripts path (using cd) then manually type "pip install -r requirements.txt" (without the "").

If there's still an error, then see the contents of the .txt file, be sure to rename it to "requirements.txt" (even if it looks like normal)

**Comment by Yharoses** [comment]
I already tried this but it keeps giving me error

**Comment by WorldObservationLog** [comment]
plz post the error output
