### ISSUE TITLE
[BUG] Pixel placing

### ISSUE THREAD

**Issue by Antoine489** [WorldObservationLog/reddit-place-script-2023#15]
# Bug Report Form

## Checklist

- [✅ ] I am using the latest version of the code.
- [ ✅ ] I am absolutely sure I read the README in its entirety.
- [✅  ] I have made sure this is not a duplicate issue.
- [✅  ] I have filled out this form correctly.

## Describe the bug

Again the code say me "Succeeded placing pixel" but  when i view the rplace nothing happens.
`

## To Reproduce

Steps to trigger the bug:

1. Go to 'Code Directory'
2. Click on 'start.bat'
3. See error

## Expected behavior

Normally the pixel have to be placed

(Sorry for bad english im not)

**Comment by Saumya-Gupta-26** [comment]
I have the same issue. The timer runs on my account but I don't see my name on the pixel-location where it should have been placed.

**Comment by Chepycou** [comment]
Same error.
I get the :
Datetag | SUCCESS  | __main__:set_pixel_and_check_ratelimit:197 - Thread # 1 - username : Succeeded placing pixel
But no pixel is placed

**Comment by Chepycou** [comment]
I'm running with debug and comparing with the actual request of pixel placing.
- Coordinates seem fine
- problem on the request?

**Comment by ghost** [comment]
https://www.reddit.com/r/RedditEng/comments/wro64p/how_we_built_rplace_2022_bots_and_safety/
Reddit have introduced strict bot detection and have shadow bans now too. you will need to get new accounts with higher total entropy

**Comment by Antoine489** [comment]
You have a solution ?

**Comment by utdorm** [comment]
Reddit introduced shadow banning

`{
    "errors": [
        {
            "message": "Ratelimited",
            "path": [
                "act"
            ],
            "extensions": {
                "nextAvailablePixelTs": 2147483647000
            }
        },
        {
            "message": "ratelimit hit, next available: 2147483647000",
            "path": [
                "act"
            ]
        }
    ],
    "data": null
}`

**Comment by WorldObservationLog** [comment]
Duplicate, see https://github.com/WorldObservationLog/reddit-place-script-2023/issues/12#issuecomment-1646741978

**Comment by Saumya-Gupta-26** [comment]
I'm not shadowbanned and I have the same issue still

**Comment by WorldObservationLog** [comment]
> I'm not shadowbanned and I have the same issue still

The shadow banning preforms randomly. Sometimes being shadow banned or being not shadow banned just happen in five minutes. To find out whether your account is not shadow banned or not, Please use an observing account to see if placing manually and placing by scripts at the same time have a same result.
