### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by DeRialPsolaGmer** [WorldObservationLog/reddit-place-script-2023#16]
# Bug Report Form

## Checklist

- [x] I am using the latest version of the code.
- [x] I am absolutely sure I read the README in its entirety.
- [x] I have made sure this is not a duplicate issue.
- [x] I have filled out this form correctly.

## Describe the bug

after execute the startverbose.bat only sometimes work showing this error: ERROR    | __main__:set_pixel_and_check_ratelimit:183 - Thread #0 - DeRialPsolaGmer: Failed placing pixel: rate limited

**Comment by RedOrchid137** [comment]
it means you're rate limited ..
