### ISSUE TITLE
Authorization failed. With Valid Accounts

### ISSUE THREAD

**Issue by JohnMama12** [WorldObservationLog/reddit-place-script-2023#20]
Steps to reproduce the bug:

1. Open Start.bat
2. 2023-07-24 10:15:31.894 | ERROR    | __main__:task:544 - Feeling_Recipe1772 - Authorization failed!
NoneType: None
2023-07-24 10:15:33.953 | ERROR    | __main__:task:544 - Swimming-Security21 - Authorization failed!
NoneType: None

I created both accounts with a custom account generator script i made. Both accounts seem to login correctly on a web browser.

**Comment by WorldObservationLog** [comment]
run startvebose.bat or startvebose.sh, then post the output

**Comment by JohnMama12** [comment]
Ok it works now. However i don't see much done at the pixel start area..  I got start cords for each user at 0,0

**Comment by WorldObservationLog** [comment]
maybe shadowban, #19 or #12
