### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by SiriusCrack** [WorldObservationLog/reddit-place-script-2023#22]
## Describe the bug

It looks like there's an issue with the pixel translation. Especially negative pixels, trying to place throws an exception. Here is an example out: [Bug output](https://pastebin.com/DMyhmwg4)

I saw you can't test any placement. Let me know if you need any testing

**Comment by WorldObservationLog** [comment]
repository has reverted to the useable version. please execuse `git pull --force`
