### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by HathHub** [WorldObservationLog/reddit-place-script-2023#23]
The coords are the ones displayed in the page UI or the ones displayed on the http query requests? as they differ, If it is the pixels displayed on the place button, the script isnt placing pixels

**Comment by WorldObservationLog** [comment]
coords displayed in the page UI. about the problem of placing, please see README.md, https://github.com/WorldObservationLog/reddit-place-script-2023/issues/12 and https://github.com/WorldObservationLog/reddit-place-script-2023/issues/19
