### ISSUE TITLE
[BUG] Pixel detection incorrect.

### ISSUE THREAD

**Issue by jamesaustin** [WorldObservationLog/reddit-place-script-2023#25]
Pixel detection is no longer correct. I assume another fix is required after the canvas size update?

Pixel write position is correct.
But Pixel read position is wrong.

**Comment by WorldObservationLog** [comment]
The display maybe wrong because I have no effort to write code to convent coords, but it should actually work.
The script has three coordinate systems and I am in a terrible fix because of it.

**Comment by jamesaustin** [comment]
If the color check is incorrect then the script will:
* skip pixels that should be written, and
* write pixels that are not required.

**Comment by WorldObservationLog** [comment]
> If the color check is incorrect then the script will:
> 
> * skip pixels that should be written, and
> * write pixels that are not required.

This version's color checking is unable to use. I tried to fix it but it caused other bugs so I had to give up. The fixed version is in dev branch.

**Comment by evans-onomerike** [comment]
I appreciate your work. I recognise how time consuming it can be to maintain a repo. Where is the dev branch?

> > If the color check is incorrect then the script will:
> > 
> > * skip pixels that should be written, and
> > * write pixels that are not required.
> 
> This version's color checking is unable to use. I tried to fix it but it caused other bugs so I had to give up. The fixed version is in dev branch.

**Comment by WorldObservationLog** [comment]
> I appreciate your work. I recognise how time consuming it can be to maintain a repo. Where is the dev branch?
> 
> > > If the color check is incorrect then the script will:
> > > 
> > > * skip pixels that should be written, and
> > > * write pixels that are not required.
> > 
> > 
> > This version's color checking is unable to use. I tried to fix it but it caused other bugs so I had to give up. The fixed version is in dev branch.

here: https://github.com/WorldObservationLog/reddit-place-script-2023/tree/dev
WARNING: This version will cause #22.

**Comment by evans-onomerike** [comment]
> > I appreciate your work. I recognise how time consuming it can be to maintain a repo. Where is the dev branch?
> > > > If the color check is incorrect then the script will:
> > > > 
> > > > * skip pixels that should be written, and
> > > > * write pixels that are not required.
> > > 
> > > 
> > > This version's color checking is unable to use. I tried to fix it but it caused other bugs so I had to give up. The fixed version is in dev branch.
> 
> here: https://github.com/WorldObservationLog/reddit-place-script-2023/tree/dev WARNING: This version will cause #22.

All of your versions seem to cause this issue with negative pixels.

**Comment by WorldObservationLog** [comment]
> > > I appreciate your work. I recognise how time consuming it can be to maintain a repo. Where is the dev branch?
> > > > > If the color check is incorrect then the script will:
> > > > > 
> > > > > * skip pixels that should be written, and
> > > > > * write pixels that are not required.
> > > > 
> > > > 
> > > > This version's color checking is unable to use. I tried to fix it but it caused other bugs so I had to give up. The fixed version is in dev branch.
> > 
> > 
> > here: https://github.com/WorldObservationLog/reddit-place-script-2023/tree/dev WARNING: This version will cause #22.
> 
> All of your versions seem to cause this issue with negative pixels.

Negative pixel? Well I never meet this problem. Is there any example?
