### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by ghost** [WorldObservationLog/reddit-place-script-2023#3]
# Bug Report Form

## Checklist

- [Y] I am using the latest version of the code.
- [Y] I am absolutely sure I read the README in its entirety.
- [Y] I have made sure this is not a duplicate issue.
- [Y] I have filled out this form correctly.

## Describe the bug

Login failure; tried so many times I got told off for doing it too much.

## To Reproduce

Steps to trigger the bug:

1. Fill-out a single worker field (mine included 2FA and failed continuously; according to the README.MD, I use a semicolon separator on the password).

2. Run the program.

3. Continuous retries until Reddit tells you off for trying it one-too-many times.

## Expected behavior

Login & Authorisation successful.

## Additional Context

You can see me being told off for too many retries here.

![cmd_2023-07-21_21-07-22](https://github.com/WorldObservationLog/reddit-place-script-2023/assets/62147514/ffdc415e-5250-453d-a4a3-d72232911699)

**Comment by ghost** [comment]
Side note, I wonder if the 2FA is related. It *should* work normally, but I can't ascertain if 2022 by rdeepak worked already with 2FA or if this is a carry-over bug if that turns out to be the problem-child.

**Comment by AtomicGerbil** [comment]
okay, so with communication to somebody, the bug is fixed by changing line 555 to:
`"passwd": password,`

maybe something API related...?

**Comment by WorldObservationLog** [comment]
Due to #2 , you may met Authorisation Failed while logging in. And because of 2FA, the 10 seconds wait for retrying will invalidate your 2FA code. If you meet this situation, just change your code in config.json and restart program.

**Comment by ghost** [comment]
I don't think that's the case.

I update the 2FA pretty much immediately and still get issues; I know the password is correct.
Just tried the most recent version but still nothing has changed.

**Comment by ghost** [comment]
Yeah, I can log into this fork of the project just fine: https://github.com/qwertyuu/reddit-place-script-2023 ; the login is successful each time.

Problem with that fork is that it doesn't read the canvas properly.

**Comment by WorldObservationLog** [comment]
Try to use colon(:) to separate your password and 2FA code. I have tested with my account with 2FA and it works.

**Comment by ghost** [comment]
I'm aware of the format labeled in `README.MD`

It is `"password" : "<password>:<2FAKey>"` as described.
I've done that and it *still* fails.

**Comment by ghost** [comment]
I'll get a `git reset --hard` to see if something screwed up in pull.

**Comment by ghost** [comment]
No dice, unfortunately. Still getting the issue.

By second or third time, the 2FA times out for a new one. I'll try disabling 2FA.

`git reset --hard` should've gutted anything bad going on.
![image](https://github.com/WorldObservationLog/reddit-place-script-2023/assets/62147514/e39ba75e-e3f4-4f2a-9a05-95e4e5e10ed8)

**Comment by ghost** [comment]
Okay, 2FA turned off. 

Going to try this one more time.
I got timed out by sending too many login requests woops.

**Comment by WorldObservationLog** [comment]
I can still not reproduce this problem. And amazingly, my account can successfully log in without 2FA code(I'm sure that I have enabled 2FA).

**Comment by WorldObservationLog** [comment]
well can you login to https://www.reddit.com/login with this credential and without 2FA?

**Comment by ghost** [comment]
I'm already logged in.

I'll log out first? 
![image](https://github.com/WorldObservationLog/reddit-place-script-2023/assets/62147514/93c3301d-350b-4b9b-87cd-8f5df1c93496)

**Comment by ghost** [comment]
I disabled 2FA and still got the same authorisation issues.

**Comment by tyl0re** [comment]
Same error on my side

**Comment by WorldObservationLog** [comment]
> I disabled 2FA and still got the same authorisation issues.

In reddit.com?

**Comment by ghost** [comment]
Yeah.

Make yer comments about 'passwords being saved in a browser' but idc about Reddit enough to care lmao.
Anyways, that password saved in my browser is the same login for the acc I'm trying to bot - I checked that vs the `config.json` data and they are the same password.

Something is going on between trying to authenticate the account, the program and Reddit.

**Comment by WorldObservationLog** [comment]
I think that's the reddit side's problem and sorry for no ability to fix it.
maybe the account change need some time to take effect.

**Comment by ghost** [comment]
Whatever it is, it should be solvable.

This fork still work and you can sign in, it just placed pixels incorrectly and doesn't account for the negative values of the canvas.
https://github.com/qwertyuu/reddit-place-script-2023

**Comment by ghost** [comment]
> I think that's the reddit side's problem and sorry for no ability to fix it. maybe the account change need some time to take effect.

It's not a Reddit issue with the above said; it is a code issue.
The above fork authenticates 100% of the time, I think the issue with it is out-dated hooks and some other things with pixel placement.

I'm confident its a code issue that can be solved.

**Comment by WorldObservationLog** [comment]
> Whatever it is, it should be solvable.
> 
> This fork still work and you can sign in, it just placed pixels incorrectly and doesn't account for the negative values of the canvas. https://github.com/qwertyuu/reddit-place-script-2023

well can you use this fork to login now? if so, please send your account name and password to wolchannel@proton.me. I am unable to reproduce it with my own account.

**Comment by ghost** [comment]
So, the difference in this fork is that it uses Pillow 9.3.0, whereas this fork uses 9.1.1

Wonder if that's partially related, and yes I could log in just fine. I'll send you the details now.

**Comment by smallest-cock** [comment]
> So, the difference in this fork is that it uses Pillow 9.3.0, whereas this fork uses 9.1.1
> 
> Wonder if that's partially related, and yes I could log in just fine. I'll send you the details now.

This fork is working for me now.. I confirmed the pixel has actually been placed on the canvas. But I'm using python 3.11 and I manually upgraded Pillow through pip. Which means I had to delete the Pillow line in `requirements.txt`

Maybe this fork can be updated to work with the latest version of python?

**Comment by ghost** [comment]
> > So, the difference in this fork is that it uses Pillow 9.3.0, whereas this fork uses 9.1.1
> > Wonder if that's partially related, and yes I could log in just fine. I'll send you the details now.
> 
> This fork is working for me now.. I confirmed the pixel has actually been placed on the canvas. But I'm using python 3.11 and I manually upgraded Pillow through pip. Which means I had to delete the Pillow line in `requirements.txt`
> 
> Maybe this fork can be updated to work with the latest version of python?

That's weird? I couldn't get it to properly place a pixel in the negative values. I refresh the page to see where it placed the pixel and the pixel spot does not update.

It 'says' it is successful, but be wary that is a false positive. It isn't even using the correct web-hook, which is not 'hot-potato' but 'garlic-bread' afaik so it 'successfully' works on a web-hook that's completely inactive.

**Comment by WorldObservationLog** [comment]
> > So, the difference in this fork is that it uses Pillow 9.3.0, whereas this fork uses 9.1.1
> > Wonder if that's partially related, and yes I could log in just fine. I'll send you the details now.
> 
> This fork is working for me now.. I confirmed the pixel has actually been placed on the canvas. But I'm using python 3.11 and I manually upgraded Pillow through pip. Which means I had to delete the Pillow line in `requirements.txt`
> 
> Maybe this fork can be updated to work with the latest version of python?

Updated in commit 4ff9e26
