### ISSUE TITLE
[BUG] Huge issue. Placing wrong colors on the canvas

### ISSUE THREAD

**Issue by Vandit2405** [WorldObservationLog/reddit-place-script-2023#9]
# Bug Report Form

## Checklist

- [ ] I am using the latest version of the code. yes
- [ ] I am absolutely sure I read the README in its entirety. yes
- [ ] I have made sure this is not a duplicate issue. yes
- [ ] I have filled out this form correctly. yes

## Describe the bug

Ok so I have a pixelated .png of the artwork. It was initially 1100x1100 or so pixels of size and i shrank it down to 69x68 to resemble the exact dimensions of the pixelated image and put the correct coordinate of the top left pixel. After the steps, when i executed the script, i started seeing that wrong colored pixels were being assigned and put by my workers. Please help. It was a mess.

Current commit hash: Replace this text with the output of `git rev-parse HEAD`

## To Reproduce

Steps to trigger the bug:

## Expected behavior

Replace this text with what _should_ have happened if no bug occurred.

**Comment by WorldObservationLog** [comment]
The color transform function uses an algorithm to calculate the similarity of colors. And I sure there is no problem with the algorithm.
It seems that the problem is your image. You should use an image drawn pixel by pixel, not an image zoomed out from other image.
